version: 2

shared: &shared
  steps:
    - checkout
    - run: yarn
    - run: yarn test:ci

jobs:
  test-node-10:
    docker:
      - image: node:10
    <<: *shared

  test-node-12:
    docker:
      - image: node:12
    <<: *shared

  test-node-13:
    docker:
      - image: node:13
    <<: *shared

workflows:
  version: 2
  test:
    jobs:
      - test-node-10
      - test-node-12
      - test-node-13
